project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Socioeconomic Influences on County-Level Voting Trends in Presidential Elections (2000-2020)"
  author:
    - Anh Lam (adl2196)
    - Long Gao (lg3385)
  repo-url: https://github.com/lg3385/EDAV_project
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


